### ISSUE TITLE
Inventory Endpoint'in Geçersiz Olması Hk.

### ISSUE THREAD

**Issue by ahmeti** [tcgunel/bizimhesap-b2b#1]
Merhaba,

Inventory endpoint kullanımdan kaldırılmış sanırım. İstekte bulunduğumda aşağıdaki mesajı alıyorum.

`The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`

Bilgi amaçlı bir issue açmak istedim. Ellerine sağlık, çok güzel bir paket hazırlamışsınız.

https://github.com/tcgunel/bizimhesap-b2b/blob/4d6f58c71de8b3a4f0f0b877976cbbfff67b0bf8/src/BizimHesapB2bInventory.php#L15

**Comment by tcgunel** [comment]
Bilgilendirme için teşekkürler.

**Comment by tcgunel** [comment]
Endpoint https://bizimhesap.com/api/b2b/inventory/{warehouse-id} olarak düzeltildi.
